let bank,state={mode:null,qs:[],i:0,score:0,answered:false,deadline:0};
const app=document.querySelector('#app'),info=document.querySelector('#info'),modal=document.querySelector('#modal');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const store=()=>JSON.parse(localStorage.getItem('cr-progress')||'{"errors":[],"attempts":0,"best":null}');
function save(x){localStorage.setItem('cr-progress',JSON.stringify(x))}
async function init(){bank=await (await fetch('data/questions-cr.json')).json();home()}
function home(){state={mode:null,qs:[],i:0,score:0,answered:false,deadline:0};info.textContent='';app.innerHTML=`<div class="wrap"><section class="hero"><span class="badge">Carte de résident · CR</span><h1>Préparez votre examen civique</h1><p class="muted">Entraînement et simulation d'examen.</p></section><div class="grid"><button class="card" id="training"><h2>🧠 Entraînement</h2><p>Correction immédiate.</p></button><button class="card" id="exam"><h2>🇫🇷 Examen blanc CR</h2><p>40 questions · 45 minutes.</p></button><button class="card" id="errors"><h2>🔁 Mes erreurs</h2><p>Revoir les questions ratées.</p></button><button class="card" id="progress"><h2>📊 Ma progression</h2><p>Voir vos résultats.</p></button></div></div>`;training.onclick=()=>start('training');exam.onclick=()=>start('exam');errors.onclick=errorsView;progress.onclick=progressView}
function start(mode){let q=shuffle(bank.questions||[]);if(mode==='exam')q=shuffle(q.slice(0,28).concat(shuffle(bank.situations_entrainement||[]).slice(0,12)));state={mode,qs:q,i:0,score:0,answered:false,deadline:mode==='exam'?Date.now()+2700000:0};render()}
function render(){let q=state.qs[state.i], order=shuffle(q.reponses.map((text,index)=>({text,index})));state.order=order;state.answered=false;info.textContent=`${state.i+1}/${state.qs.length}`;app.innerHTML=`<div class="wrap"><section class="hero"><span class="badge">${state.mode==='exam'?'Examen CR':'Entraînement'}</span>${state.mode==='exam'?'<p id="timer"></p>':''}<div class="progress"><div style="width:${state.i/state.qs.length*100}%"></div></div><p class="muted">${esc(q.theme||q.id||'Question')}</p><h2>${esc(q.enonce)}</h2><div class="answers">${order.map((a,i)=>`<button class="answer" data-i="${i}">${esc(a.text)}</button>`).join('')}</div><div id="feedback"></div><button id="next" class="btn" disabled>${state.i===state.qs.length-1?'Terminer':'Question suivante →'}</button></section></div>`;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.i));next.onclick=goNext;if(state.mode==='exam')timer()}
function answer(i){if(state.answered)return;state.answered=true;let q=state.qs[state.i],correct=state.order[i].index===q.bonne;if(correct)state.score++;document.querySelectorAll('.answer').forEach((b,j)=>{if(state.order[j].index===q.bonne)b.classList.add('correct');if(j===i&&!correct)b.classList.add('wrong')});if(state.mode==='training')document.querySelector('#feedback').innerHTML=`<p><b>${correct?'✅ Bonne réponse':'❌ Mauvaise réponse'}</b></p><p class="muted">${esc(q.explication||'')}</p>`;next.disabled=false;if(!correct){let s=store();if(q.id&&!s.errors.includes(q.id))s.errors.push(q.id);save(s)}if(state.mode==='training')setTimeout(()=>{if(state.answered)goNext()},1400)}
function goNext(){if(!state.answered)return;if(state.i===state.qs.length-1)return finish();state.i++;render()}
function finish(){let s=store();if(state.mode==='exam'){s.attempts++;s.best=s.best===null?state.score:Math.max(s.best,state.score);save(s)}app.innerHTML=`<div class="wrap"><section class="result"><h1>${state.mode==='exam'?(state.score>=32?'Réussi ✅':'À revoir'):'Session terminée'}</h1><div class="score">${state.score} / ${state.qs.length}</div>${state.mode==='exam'?`<p>${state.qs.length-state.score} erreur(s) · Seuil : 32 / 40</p>`:''}<button class="btn" onclick="home()">Retour au menu</button></section></div>`;info.textContent=''}
function progressView(){let s=store();app.innerHTML=`<div class="wrap"><section class="hero"><h1>Ma progression</h1><p>Examens réalisés : <b>${s.attempts}</b></p><p>Meilleur score : <b>${s.best===null?'—':s.best+' / 40'}</b></p><p>Questions à revoir : <b>${s.errors.length}</b></p><button class="btn" onclick="home()">← Menu</button></section></div>`}
function errorsView(){let ids=new Set(store().errors),qs=(bank.questions||[]).filter(q=>ids.has(q.id));app.innerHTML=`<div class="wrap"><section class="hero"><h1>Mes erreurs</h1><p>${qs.length?qs.length+' question(s) à revoir.':'Aucune erreur enregistrée.'}</p><button class="btn" onclick="home()">← Menu</button></section></div>`}
function timer(){let e=document.querySelector('#timer');let tick=()=>{if(!e||state.mode!=='exam')return;let x=Math.max(0,state.deadline-Date.now()),m=Math.floor(x/60000),s=Math.floor(x/1000)%60;e.textContent=`⏱ ${m}:${String(s).padStart(2,'0')}`;if(x<=0){state.answered=true;finish()}else setTimeout(tick,1000)};tick()}
document.querySelector('#menu').onclick=()=>{if(state.mode)modal.hidden=false;else home()};document.querySelector('#stay').onclick=()=>modal.hidden=true;document.querySelector('#leave').onclick=()=>{modal.hidden=true;home()};init().catch(e=>app.innerHTML=`<div class="wrap"><section class="hero"><h1>Erreur de chargement</h1><p>${esc(e.message)}</p></section></div>`);
